CREATE TABLE USER (
	U_ID INT,
	Email VARCHAR(30) NOT NULL,
	Username VARCHAR(15) NOT NULL,
	Password VARCHAR(20) NOT NULL,
	Phone_number CHAR(13),
	PRIMARY KEY (U_ID)
	);
CREATE TABLE STORAGE_LOCATION (
	U_ID INT,
	S_ID INT,
	Location VARCHAR(30),
	Name VARCHAR(30),
	Temp INT,
	PRIMARY KEY (S_ID),
	FOREIGN KEY (U_ID) REFERENCES USER(U_ID)
	);
CREATE TABLE FOOD (
	F_ID INT,
	S_ID INT,
	Name VARCHAR(30) NOT NULL,
	Type INT,
	Time_added DATE,
	Exp_date DATE NOT NULL,
	Quantity INT,
	PRIMARY KEY (F_ID),
	FOREIGN KEY (S_ID) REFERENCES STORAGE_LOCATION(S_ID)
	);
CREATE TABLE NUTRITION (
	F_ID INT,
	Calories INT,
	Servings INT,
	Ingredients VARCHAR(30),
	Allergens VARCHAR(30),
	FOREIGN KEY (F_ID) REFERENCES FOOD(F_ID)
	);
CREATE TABLE RECIPE (
	R_ID INT,
	U_ID INT,
	Ingredients INT NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Prep_time INT,
	Instructions VARCHAR(200) NOT NULL,
	PRIMARY KEY (R_ID),
	FOREIGN KEY (U_ID) REFERENCES USER(U_ID)
);